# Generated by Django 5.2.7 on 2025-10-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='room_num',
            field=models.IntegerField(default=0),
        ),
    ]
